CartedDish.create!([
  {status: "removed", user_id: 2, dish_id: 1, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 4, quantity: 2, order_id: 1, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 21, quantity: 1, order_id: 1, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 9, quantity: 1, order_id: 2, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 26, quantity: 1, order_id: 2, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 4, quantity: 2, order_id: 2, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 1, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 3, order_id: 3, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 9, quantity: 3, order_id: 3, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 4, quantity: 3, order_id: 3, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 15, quantity: 3, order_id: 3, session_id: nil},
  {status: "purchased", user_id: 3, dish_id: 9, quantity: 2, order_id: 4, session_id: nil},
  {status: "purchased", user_id: 3, dish_id: 11, quantity: 1, order_id: 4, session_id: nil},
  {status: "removed", user_id: 3, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 3, dish_id: 4, quantity: 3, order_id: 5, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 9, quantity: 1, order_id: 6, session_id: nil},
  {status: "removed", user_id: 3, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 9, quantity: 1, order_id: 7, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 9, quantity: 1, order_id: 8, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 19, quantity: 1, order_id: 9, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 4, quantity: 1, order_id: 9, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 9, session_id: nil},
  {status: "removed", user_id: 4, dish_id: 21, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 4, dish_id: 4, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 4, dish_id: 1, quantity: 1, order_id: 10, session_id: nil},
  {status: "purchased", user_id: 4, dish_id: 9, quantity: 1, order_id: 11, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 7, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 18, quantity: 1, order_id: 12, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 4, quantity: 1, order_id: 12, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 13, session_id: nil},
  {status: "purchased", user_id: 5, dish_id: 4, quantity: 7, order_id: 14, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 1, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 15, session_id: nil},
  {status: "removed", user_id: 6, dish_id: 1, quantity: 2, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 6, dish_id: 7, quantity: 1, order_id: 16, session_id: nil},
  {status: "purchased", user_id: 7, dish_id: 9, quantity: 1, order_id: 17, session_id: nil},
  {status: "purchased", user_id: 7, dish_id: 4, quantity: 3, order_id: 17, session_id: nil},
  {status: "removed", user_id: 8, dish_id: 9, quantity: 2, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 8, dish_id: 1, quantity: 1, order_id: 18, session_id: nil},
  {status: "purchased", user_id: 8, dish_id: 7, quantity: 1, order_id: 18, session_id: nil},
  {status: "purchased", user_id: 8, dish_id: 22, quantity: 1, order_id: 19, session_id: nil},
  {status: "removed", user_id: 8, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 8, dish_id: 1, quantity: 2, order_id: 20, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 21, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 1, quantity: 1, order_id: nil, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 6, quantity: 1, order_id: 22, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 4, quantity: 1, order_id: 22, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 22, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 23, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 25, quantity: 1, order_id: 24, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 24, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 18, quantity: 1, order_id: 24, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 18, quantity: 1, order_id: 24, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 12, quantity: 34, order_id: 24, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 25, quantity: 1, order_id: 25, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 25, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 18, quantity: 1, order_id: 25, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 18, quantity: 1, order_id: 26, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 33, quantity: 2, order_id: 26, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 37, quantity: 1, order_id: 26, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 27, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 27, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 28, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 30, quantity: 1, order_id: 28, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 28, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 29, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 30, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 26, quantity: 1, order_id: 30, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 31, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 32, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 34, quantity: 1, order_id: 33, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 30, quantity: 1, order_id: 34, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 25, quantity: 1, order_id: 35, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 37, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 38, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 39, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 40, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 11, quantity: 1, order_id: 41, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 30, quantity: 1, order_id: 42, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 43, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 44, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 1, quantity: 1, order_id: 46, session_id: nil},
  {status: "purchased", user_id: 2, dish_id: 14, quantity: 1, order_id: 47, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 14, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 6, dish_id: 24, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 5, dish_id: 1, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 6, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 1, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 8, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 20, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 7, dish_id: 9, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 14, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 14, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: 2, dish_id: 14, quantity: 1, order_id: nil, session_id: nil},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 14, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 14, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 34, quantity: 2, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 4, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 26, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "removed", user_id: nil, dish_id: 26, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"},
  {status: "carted", user_id: nil, dish_id: 1, quantity: 1, order_id: nil, session_id: "d7010de3115fa93357a04f9f3f6aef63"}
])
Category.create!([
  {name: "Sundaes", tagline: "Bursting With Fun"},
  {name: "Grillers", tagline: "Bursting With Taste"},
  {name: "Drinks", tagline: "Bursting With Flavor"},
  {name: "Salads", tagline: "Bursting With Goodness"}
])
Dish.create!([
  {name: "American Three Cheese", description: "•Mozzerella Cheese •Pepper Jack Cheese •Parmesan Cheese •Sliced Tomatoes •Fresh Sliced Mushrooms", price: "10.95", category_id: 3, subcategory_id: nil},
  {name: "The Colorush", description: "•Vanilla Ice Cream •Vanilla ‘n’ Cherry Ice Cream •Whipped Cream •Fruit Loops •M&M’s •Raspberry Sauce •Cherry ", price: "6.95", category_id: 1, subcategory_id: nil},
  {name: "Hearts Of Palm Salad", description: "•Cubed Hearts of Palm •Avocado •Red Onions •Tomatoes •Persian Cucumbers •Mini Croutons •Baby Arugula •Iceberg Lettuce •Red Wine Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Exotic Euro Salad", description: "•Grilled Peaches •Cubed Mango •Craisins •Popped Quinoa •Glazed Almond Sticks •Baby Arugula •Romaine Lettuce •Raspberry Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Roasted Mushroom Salad", description: "•Portabella Mushrooms •Cremini Mushrooms •Red Onions •Fire Roasted Red Peppers •Nish Nosh Crackers •Romaine Lettuce •Balsamic Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Eggplant Parmesan Salad", description: "•Sliced Roasted Eggplant •Homemade Croutons •Roasted Grape Tomatoes •Parmesan Cheese •Shredded Cheese •Romaine  •Lettuce Herbed Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Middle Eastern Tilapia", description: "•Schwarma Tilapia •Sliced Tomatoes •Cucumbers •Chick Peas •Sour Pickles •Red Onions •Hot Peppers (optional)", price: "10.95", category_id: 3, subcategory_id: nil},
  {name: "Italian Parmesan", description: "•Grilled Eggplant •Baby Arugula •Sliced Tomatoes •Crispy Fried Onions •Shredded Cheese •Parmesan Cheese", price: "8.95", category_id: 3, subcategory_id: nil},
  {name: "Authentic Mexican", description: "•Sliced Avocado •Sliced Tomato •Fresh Peppers •Surprise Jalepeno •Red Cabbage •Pepper Jack Cheese •Baby Spinach", price: "8.95", category_id: 3, subcategory_id: nil},
  {name: "Greek Island", description: "•Black Olives •Feta Cheese •Cucumbers •Roasted Button Mushrooms •Red Onions •Tomatoes •Romaine lettuce •Baby Spinach", price: "8.95", category_id: 3, subcategory_id: nil},
  {name: "Kiddie Griller", description: "•Pizza Sauce and Cheese", price: "5.95", category_id: 3, subcategory_id: nil},
  {name: "Cookies 'n' Cream", description: nil, price: "6.95", category_id: 4, subcategory_id: 1},
  {name: "Wild Strawberry", description: nil, price: "6.95", category_id: 4, subcategory_id: 1},
  {name: "The Ultimate Chiller", description: nil, price: "7.95", category_id: 4, subcategory_id: 1},
  {name: "Asian Salmon", description: "•Five Spice Salmon •Red Cabbage •Cucumbers •Julienned Carrots •Baby Spinach •Romaine Lettuce", price: "10.95", category_id: 3, subcategory_id: nil},
  {name: "Create Your Own Razzle", description: nil, price: "7.95", category_id: 4, subcategory_id: 1},
  {name: "Tuna Melt", description: "•Tuna •Tomatoes •Cucumbers •Red Pepper •Sour Pickles •Red Onions •Shredded Cheese •Hot Peppers (optional)", price: "10.95", category_id: 3, subcategory_id: nil},
  {name: "Double Chocolate", description: nil, price: "6.95", category_id: 4, subcategory_id: 1},
  {name: "The Cookie Crumble", description: "•Crumbled Oreo Cookies •Vanilla Ice Cream •Cookies ‘n’ Cream Ice Cream •Whipped Cream •Hot Fudge •Mini Oreo Cookies •Cherry", price: "7.95", category_id: 1, subcategory_id: nil},
  {name: "Frapp In A Bowl", description: "•Tiramisu Ice Cream •Chocolate Ice Cream •Caramel Sauce •Coffee Sauce •Whipped Cream •Cappuccino Chips •Cherry", price: "9.95", category_id: 1, subcategory_id: nil},
  {name: "Sweet Potato Salad", description: "•Roasted Sweet Potato •Roasted Butternut Squash •Julienned Fennel •Granny Smith Apples •Glazed Almond Sticks •Baby Arugula •Maple Dijon Dressing", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Sea Breeze Salad", description: "•Five Spice Salmon •Cucumbers •Julienned Carrots •Purple Cabbage •Chinese Noodles •Baby Spinach •Iceberg Lettuce •Orange Vinaigrette", price: "16.95", category_id: 2, subcategory_id: nil},
  {name: "Benihana Salad", description: "•Mandarin Oranges •Baby Corn •Fresh Tomatoes •Persian Cucumbers •Glazed Almonds •Chinese Noodles •Baby Arugala •Ginger Dressing", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Chop Style", description: "•Grilled Portabella Mushrooms •Grilled Tomatoes •Roasted Red Peppers •Crispy Fried Onions •Baby Spinach •Shredded Cheese", price: "10.95", category_id: 3, subcategory_id: nil},
  {name: "Creamy Peanut Butter", description: nil, price: "6.95", category_id: 4, subcategory_id: 1},
  {name: "Go Mango", description: nil, price: "6.95", category_id: 4, subcategory_id: 2},
  {name: "Blue Banana", description: "(made with milk)", price: "6.95", category_id: 4, subcategory_id: 2},
  {name: "Tropical Chill", description: nil, price: "6.95", category_id: 4, subcategory_id: 2},
  {name: "Strawbana", description: "(made with milk)", price: "6.95", category_id: 4, subcategory_id: 2},
  {name: "Strawberry Sub 'Lime'", description: nil, price: "6.95", category_id: 4, subcategory_id: 2},
  {name: "Just Peachy", description: nil, price: "6.95", category_id: 4, subcategory_id: 2},
  {name: "Limonana On The Rocks", description: "(Sugar Free)", price: "3.99", category_id: 4, subcategory_id: 3},
  {name: "Frozen Limonana", description: "(Sugar Free)", price: "3.99", category_id: 4, subcategory_id: 3},
  {name: "Blue Mango Smoothie", description: "(No Sugar Added)", price: "7.95", category_id: 4, subcategory_id: 3},
  {name: "Go Mango Smoothie", description: "(No Sugar Added)", price: "7.95", category_id: 4, subcategory_id: 3},
  {name: "The S'mores The Better", description: "•Graham Crackers •Vanilla Ice Cream •Chocolate Ice Cream •Hot Fudge •Marshmallow •Whipped Cream •Nut Crunch •Cherry ", price: "7.95", category_id: 1, subcategory_id: nil},
  {name: "Bourbon Caramel", description: "•Butter Pecan Ice Cream •Vanilla Ice Cream •Chinese Pecans •Bourbon Caramel Sauce •Hot Caramel Sauce •Whipped Cream •Coffee liqueur •Cherry", price: "9.95", category_id: 1, subcategory_id: nil},
  {name: "The Peanut Butter Cup", description: "•Chopped Peanuts •Butter Pecan Ice Cream •Tiramisu Ice Cream •Peanut Butter Sauce •Whipped Cream •Hot Fudge •Cherry", price: "7.95", category_id: 1, subcategory_id: nil},
  {name: "Spiked Chocolate Brownies", description: "•Brownie Fudge •Chocolate Ice Cream •Caramel Fudge Ice Cream •Chocolate liqueur •Hot Fudge •Whipped Cream •Brownie Crumbs •Cherry", price: "9.95", category_id: 1, subcategory_id: nil},
  {name: "Banana Split", description: "•1 Banana Split •Vanilla Ice Cream •Mint Chip Ice Cream •Vanilla Cherry Ice Cream •Whipped Cream •Chocolate Sauce •Caramel Sauce •Strawberry Sauce •Coconut Crunch •Cherry", price: "9.95", category_id: 1, subcategory_id: nil},
  {name: "Citrus Salad", description: "•Sliced Orange •Sliced Grapefruit •Cubed Avocados •Candied Beets •Craisins •Romaine Lettuce •Lemon Poppy Dressing", price: "11.95", category_id: 2, subcategory_id: nil},
  {name: "Create Your Own", description: "•Leafy Green Upgrades - $1.50 •Deluxe Toppings - $2.50 •Premium Toppings - $6.50", price: "10.95", category_id: 2, subcategory_id: nil},
  {name: "Italian Salad", description: "•Sliced Persian Cucumbers •Fresh Mushrooms •Grape Tomatoes •Julienned Carrots •Homemade Croutons •Iceberg Lettuce •Romaine Lettuce •Creamy Italian Dressing\r", price: "11.95", category_id: 2, subcategory_id: nil}
])
Order.create!([
  {subtotal: "23.85", tax: "2.15", total: "26.0"},
  {subtotal: "33.8", tax: "3.04", total: "36.84"},
  {subtotal: "116.4", tax: "10.48", total: "126.88"},
  {subtotal: "32.85", tax: "2.96", total: "35.81"},
  {subtotal: "23.85", tax: "2.15", total: "26.0"},
  {subtotal: "11.95", tax: "1.08", total: "13.03"},
  {subtotal: "11.95", tax: "1.08", total: "13.03"},
  {subtotal: "11.95", tax: "1.08", total: "13.03"},
  {subtotal: "21.85", tax: "1.97", total: "23.82"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "11.95", tax: "1.08", total: "13.03"},
  {subtotal: "14.9", tax: "1.34", total: "16.24"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "55.65", tax: "5.01", total: "60.66"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "11.95", tax: "1.08", total: "13.03"},
  {subtotal: "35.8", tax: "3.22", total: "39.02"},
  {subtotal: "18.9", tax: "1.7", total: "20.6"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "13.9", tax: "1.25", total: "15.15"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "24.85", tax: "2.24", total: "27.09"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "336.1", tax: "30.25", total: "366.35"},
  {subtotal: "24.85", tax: "2.24", total: "27.09"},
  {subtotal: "37.8", tax: "3.4", total: "41.2"},
  {subtotal: "13.9", tax: "1.25", total: "15.15"},
  {subtotal: "27.85", tax: "2.51", total: "30.36"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "12.9", tax: "1.16", total: "14.06"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "11.95", tax: "1.08", total: "13.03"},
  {subtotal: "9.95", tax: "0.9", total: "10.85"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "0.0", tax: "0.0", total: "0.0"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "8.95", tax: "0.81", total: "9.76"},
  {subtotal: "9.95", tax: "0.9", total: "10.85"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"},
  {subtotal: "0.0", tax: "0.0", total: "0.0"},
  {subtotal: "6.95", tax: "0.63", total: "7.58"},
  {subtotal: "10.95", tax: "0.99", total: "11.94"}
])
Subcategory.create!([
  {name: "Mixed Chillers", category_id: 4},
  {name: "Fruit Smoothies", category_id: 4},
  {name: "Go Lite", category_id: 4}
])
User.create!([
  {name: "Dovid", email: "dovidklaver@gmail.com", password_digest: "$2a$10$qFjU3Y0xbnYyJPTYdkJNT.Ds651eEkYoDuda.1PWG08wdMElCkcGW", admin: false},
  {name: "David", email: "davidjklaver@gmail.com", password_digest: "$2a$10$Vp16rx8O2alPHr0pnhuuiOuHf6jq6JIhwQ3GAjk8xNlB69xzh2sOu", admin: true},
  {name: "dk", email: "dk@gmail.com", password_digest: "$2a$10$NWhcX2HWmOm4iIPxkt33VOdFVf0pn/Ot9b.iuq74ZxfPlRygKeP/q", admin: false},
  {name: "Dave", email: "dave@gmail.com", password_digest: "$2a$10$XlRipq6JuDKQtgRaOzp5NOlra6bsrLPVqpcJmctwSOCDd98wXsc7a", admin: false},
  {name: "chaim klaver", email: "chaimklaver@gmail.com", password_digest: "$2a$10$306GG3ZZyudiktQcoDjeauRkW5Ti0nwErLqeF/zo1JpSDagCH2GkC", admin: false},
  {name: "chayala klaver", email: "chay613@gmail.com", password_digest: "$2a$10$z49RgtKn4rqMPn4iswIEy.9MVgbzSqhAgm69tJpOzTPKxp/sRAsK6", admin: false},
  {name: "Mark", email: "mark@gmail.com", password_digest: "$2a$10$fuVXhWDZykFW1jG6X2tjT.Xsa4kYo27gLOAt383UYwTpx0wQXIxOS", admin: false},
  {name: "Malki", email: "malkilevine@gmail.com", password_digest: "$2a$10$dizVBlPenbXFAoU4zac8Bu.wNxt5hDrX1SCO0R4umy6LWcicWk2mm", admin: false}
])
