Category.destroy_all
Category.create!([
  {name: "Sundaes", tagline: "Bursting With Fun"},
  {name: "Grillers", tagline: "Bursting With Taste"},
  {name: "Drinks", tagline: "Bursting With Flavor"},
  {name: "Salads", tagline: "Bursting With Goodness"}
])

Dish.destroy_all
Dish.create!([
  {name: "American Three Cheese", description: "•Mozzerella Cheese •Pepper Jack Cheese •Parmesan Cheese •Sliced Tomatoes •Fresh Sliced Mushrooms", price: "10.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "The Colorush", description: "•Vanilla Ice Cream •Vanilla ‘n’ Cherry Ice Cream •Whipped Cream •Fruit Loops •M&M’s •Raspberry Sauce •Cherry ", price: "6.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Hearts Of Palm Salad", description: "•Cubed Hearts of Palm •Avocado •Red Onions •Tomatoes •Persian Cucumbers •Mini Croutons •Baby Arugula •Iceberg Lettuce •Red Wine Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Exotic Euro Salad", description: "•Grilled Peaches •Cubed Mango •Craisins •Popped Quinoa •Glazed Almond Sticks •Baby Arugula •Romaine Lettuce •Raspberry Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Roasted Mushroom Salad", description: "•Portabella Mushrooms •Cremini Mushrooms •Red Onions •Fire Roasted Red Peppers •Nish Nosh Crackers •Romaine Lettuce •Balsamic Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Eggplant Parmesan Salad", description: "•Sliced Roasted Eggplant •Homemade Croutons •Roasted Grape Tomatoes •Parmesan Cheese •Shredded Cheese •Romaine  •Lettuce Herbed Vinaigrette", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Middle Eastern Tilapia", description: "•Schwarma Tilapia •Sliced Tomatoes •Cucumbers •Chick Peas •Sour Pickles •Red Onions •Hot Peppers (optional)", price: "10.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Italian Parmesan", description: "•Grilled Eggplant •Baby Arugula •Sliced Tomatoes •Crispy Fried Onions •Shredded Cheese •Parmesan Cheese", price: "8.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Authentic Mexican", description: "•Sliced Avocado •Sliced Tomato •Fresh Peppers •Surprise Jalepeno •Red Cabbage •Pepper Jack Cheese •Baby Spinach", price: "8.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Greek Island", description: "•Black Olives •Feta Cheese •Cucumbers •Roasted Button Mushrooms •Red Onions •Tomatoes •Romaine lettuce •Baby Spinach", price: "8.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Kiddie Griller", description: "•Pizza Sauce and Cheese", price: "5.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Cookies 'n' Cream", description: nil, price: "6.95", category_id: 4, subcategory_id: 1, dressing: nil},
  {name: "Wild Strawberry", description: nil, price: "6.95", category_id: 4, subcategory_id: 1, dressing: nil},
  {name: "The Ultimate Chiller", description: nil, price: "7.95", category_id: 4, subcategory_id: 1, dressing: nil},
  {name: "Asian Salmon", description: "•Five Spice Salmon •Red Cabbage •Cucumbers •Julienned Carrots •Baby Spinach •Romaine Lettuce", price: "10.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Create Your Own Razzle", description: nil, price: "7.95", category_id: 4, subcategory_id: 1, dressing: nil},
  {name: "Tuna Melt", description: "•Tuna •Tomatoes •Cucumbers •Red Pepper •Sour Pickles •Red Onions •Shredded Cheese •Hot Peppers (optional)", price: "10.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Double Chocolate", description: nil, price: "6.95", category_id: 4, subcategory_id: 1, dressing: nil},
  {name: "The Cookie Crumble", description: "•Crumbled Oreo Cookies •Vanilla Ice Cream •Cookies ‘n’ Cream Ice Cream •Whipped Cream •Hot Fudge •Mini Oreo Cookies •Cherry", price: "7.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Frapp In A Bowl", description: "•Tiramisu Ice Cream •Chocolate Ice Cream •Caramel Sauce •Coffee Sauce •Whipped Cream •Cappuccino Chips •Cherry", price: "9.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Sweet Potato Salad", description: "•Roasted Sweet Potato •Roasted Butternut Squash •Julienned Fennel •Granny Smith Apples •Glazed Almond Sticks •Baby Arugula •Maple Dijon Dressing", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Sea Breeze Salad", description: "•Five Spice Salmon •Cucumbers •Julienned Carrots •Purple Cabbage •Chinese Noodles •Baby Spinach •Iceberg Lettuce •Orange Vinaigrette", price: "16.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Benihana Salad", description: "•Mandarin Oranges •Baby Corn •Fresh Tomatoes •Persian Cucumbers •Glazed Almonds •Chinese Noodles •Baby Arugala •Ginger Dressing", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Chop Style", description: "•Grilled Portabella Mushrooms •Grilled Tomatoes •Roasted Red Peppers •Crispy Fried Onions •Baby Spinach •Shredded Cheese", price: "10.95", category_id: 3, subcategory_id: nil, dressing: nil},
  {name: "Creamy Peanut Butter", description: nil, price: "6.95", category_id: 4, subcategory_id: 1, dressing: nil},
  {name: "Go Mango", description: nil, price: "6.95", category_id: 4, subcategory_id: 2, dressing: nil},
  {name: "Blue Banana", description: "(made with milk)", price: "6.95", category_id: 4, subcategory_id: 2, dressing: nil},
  {name: "Tropical Chill", description: nil, price: "6.95", category_id: 4, subcategory_id: 2, dressing: nil},
  {name: "Strawbana", description: "(made with milk)", price: "6.95", category_id: 4, subcategory_id: 2, dressing: nil},
  {name: "Strawberry Sub 'Lime'", description: nil, price: "6.95", category_id: 4, subcategory_id: 2, dressing: nil},
  {name: "Just Peachy", description: nil, price: "6.95", category_id: 4, subcategory_id: 2, dressing: nil},
  {name: "Limonana On The Rocks", description: "(Sugar Free)", price: "3.99", category_id: 4, subcategory_id: 3, dressing: nil},
  {name: "Frozen Limonana", description: "(Sugar Free)", price: "3.99", category_id: 4, subcategory_id: 3, dressing: nil},
  {name: "Blue Mango Smoothie", description: "(No Sugar Added)", price: "7.95", category_id: 4, subcategory_id: 3, dressing: nil},
  {name: "Go Mango Smoothie", description: "(No Sugar Added)", price: "7.95", category_id: 4, subcategory_id: 3, dressing: nil},
  {name: "The S'mores The Better", description: "•Graham Crackers •Vanilla Ice Cream •Chocolate Ice Cream •Hot Fudge •Marshmallow •Whipped Cream •Nut Crunch •Cherry ", price: "7.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Bourbon Caramel", description: "•Butter Pecan Ice Cream •Vanilla Ice Cream •Chinese Pecans •Bourbon Caramel Sauce •Hot Caramel Sauce •Whipped Cream •Coffee liqueur •Cherry", price: "9.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "The Peanut Butter Cup", description: "•Chopped Peanuts •Butter Pecan Ice Cream •Tiramisu Ice Cream •Peanut Butter Sauce •Whipped Cream •Hot Fudge •Cherry", price: "7.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Spiked Chocolate Brownies", description: "•Brownie Fudge •Chocolate Ice Cream •Caramel Fudge Ice Cream •Chocolate liqueur •Hot Fudge •Whipped Cream •Brownie Crumbs •Cherry", price: "9.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Banana Split", description: "•1 Banana Split •Vanilla Ice Cream •Mint Chip Ice Cream •Vanilla Cherry Ice Cream •Whipped Cream •Chocolate Sauce •Caramel Sauce •Strawberry Sauce •Coconut Crunch •Cherry", price: "9.95", category_id: 1, subcategory_id: nil, dressing: nil},
  {name: "Citrus Salad", description: "•Sliced Orange •Sliced Grapefruit •Cubed Avocados •Candied Beets •Craisins •Romaine Lettuce •Lemon Poppy Dressing", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Create Your Own", description: "•Leafy Green Upgrades - $1.50 •Deluxe Toppings - $2.50 •Premium Toppings - $6.50", price: "10.95", category_id: 2, subcategory_id: nil, dressing: nil},
  {name: "Italian Salad", description: "•Sliced Persian Cucumbers •Fresh Mushrooms •Grape Tomatoes •Julienned Carrots •Homemade Croutons •Iceberg Lettuce •Romaine Lettuce •Creamy Italian Dressing\r", price: "11.95", category_id: 2, subcategory_id: nil, dressing: nil}
])

Image.destroy_all
Image.create!([
  {file_name: "ChopandChill2-1.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-2.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-3.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-4.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-5.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-6.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-7.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-8.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-9.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-10.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-11.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-12.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-13.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-14.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-15.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-16.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-17.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-18.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-19.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-20.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-21.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-22.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-23.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-24.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-25.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-26.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-27.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-28.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-29.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-30.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-31.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-32.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-33.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-34.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-35.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-36.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-37.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-38.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-39.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-40.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-41.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-42.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-43.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-44.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-45.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-46.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-47.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-48.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-49.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-50.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-51.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-52.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-53.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-54.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-55.jpg", dish_id: nil, salad_topping_id: nil},
  {file_name: "ChopandChill2-56.jpg", dish_id: nil, salad_topping_id: nil}
])

SaladIngredient.destroy_all
SaladIngredient.create!([
  {name: "Green Olives", image: "ChopandChill2-3.jpg"},
  {name: "Grapefruit", image: "ChopandChill2-4.jpg"},
  {name: "Shredded Carrots", image: "ChopandChill2-5.jpg"},
  {name: "Peaches", image: "ChopandChill2-6.jpg"},
  {name: "Radish", image: "ChopandChill2-7.jpg"},
  {name: "Black Bean Salsa ", image: "ChopandChill2-8.jpg"},
  {name: "Sliced Apple", image: "ChopandChill2-9.jpg"},
  {name: "Red Beets", image: "ChopandChill2-10.jpg"},
  {name: "Seasoned Chick Peas", image: "ChopandChill2-11.jpg"},
  {name: "Red Onion", image: "ChopandChill2-12.jpg"},
  {name: "Hearts of Palm", image: "ChopandChill2-13.jpg"},
  {name: "Tomatoes", image: "ChopandChill2-14.jpg"},
  {name: "Roasted Grape Tomatoes", image: "ChopandChill2-15.jpg"},
  {name: "Cucumber", image: "ChopandChill2-16.jpg"},
  {name: "Pickles", image: "ChopandChill2-17.jpg"},
  {name: "Grape Tomatoes", image: "ChopandChill2-18.jpg"},
  {name: "Fennel", image: "ChopandChill2-19.jpg"},
  {name: "Mandarin Oranges", image: "ChopandChill2-20.jpg"},
  {name: "Sauteed Onions", image: "ChopandChill2-21.jpg"},
  {name: "White Mushrooms", image: "ChopandChill2-22.jpg"},
  {name: "Baby Corn", image: "ChopandChill2-23.jpg"},
  {name: "Roasted Portabellas", image: "ChopandChill2-24.jpg"},
  {name: "Roasted Button Mushrooms", image: "ChopandChill2-25.jpg"},
  {name: "Breaded Eggplant", image: "ChopandChill2-26.jpg"},
  {name: "Roasted Butternut Squash", image: "ChopandChill2-27.jpg"},
  {name: "Seasoned Sweet Potatoes", image: "ChopandChill2-28.jpg"},
  {name: "Hot Pepper Rings", image: "ChopandChill2-29.jpg"},
  {name: "Egg Salad", image: "ChopandChill2-30.jpg"},
  {name: "Pepper Jack Cheese", image: "ChopandChill2-32.jpg"},
  {name: "Shredded Mozzarella/Cheddar", image: "ChopandChill2-33.jpg"},
  {name: "Roasted Eggplant", image: "ChopandChill2-34.jpg"},
  {name: "Roasted Red Pepper", image: "ChopandChill2-35.jpg"},
  {name: "Hard Boiled Eggs", image: "ChopandChill2-36.jpg"},
  {name: "Red Pepper", image: "ChopandChill2-41.jpg"},
  {name: "Crispy Fried Onions", image: "ChopandChill2-42.jpg"},
  {name: "Glazed Almonds", image: "ChopandChill2-43.jpg"},
  {name: "Sunflower Seeds", image: "ChopandChill2-44.jpg"},
  {name: "Croutons", image: "ChopandChill2-45.jpg"},
  {name: "Nish Nosh crackers", image: "ChopandChill2-46.jpg"},
  {name: "Chinese Noodles", image: "ChopandChill2-47.jpg"},
  {name: "Pumpkin Seeds", image: "ChopandChill2-48.jpg"},
  {name: "Cashews", image: "ChopandChill2-49.jpg"},
  {name: "Corn Nuts", image: "ChopandChill2-50.jpg"}
])

Subcategory.destroy_all
Subcategory.create!([
  {name: "Mixed Chillers", category_id: 4},
  {name: "Fruit Smoothies", category_id: 4},
  {name: "Go Lite", category_id: 4}
])
